import { beforeAll, afterEach, beforeEach, describe, expect, it } from 'vitest';

import { ScriptorView } from './view';

// Loading a real .docx, in a browser, on purpose.
//
// The obvious reading of this file is "check the parser works", and that would be redundant: the
// Rust suite asserts paragraph structure, style names and run properties natively, in about a
// millisecond, and the corpus gate covers 1,347 documents.
//
// The reason it earns its place is the target. There is no wasm_bindgen_test in this repo and
// `cargo test` runs on the host triple, so every Rust test executes on 64-bit native. The
// wasm32-unknown-unknown build - the artifact that actually ships to browsers - is compiled in CI
// and otherwise never run. This file is the only place it executes.
//
// That distinction has already bitten once: the metafile record walk needed checked_add/checked_mul
// because `usize` is 32-bit on wasm32. On x86_64 those products cannot overflow, so no native test
// can regress-catch it. So the assertions here deliberately stay off ground Rust already covers and
// stick to "the shipped build parsed real OOXML, laid it out, painted it, and gave the bytes back".

// Generated by scripts/make-rich-fixture.mjs, and generated rather than vendored because the
// LibreOffice corpus is not redistributable. Sixteen parts, chosen so most of them are things the
// model does not model - custom document properties, a theme, a font table, an embedded binary
// object, a PNG - because those are what the passthrough guarantee is about. Vitest's browser server
// is rooted at the repo root, so the crate fixture is served as-is.
const FIXTURE = '/crates/scriptor-crdt/tests/fixtures/rich.docx';

let sample: Uint8Array;
let container: HTMLDivElement;
let view: ScriptorView;

const painted = () =>
  new Promise<void>((r) => requestAnimationFrame(() => requestAnimationFrame(() => r())));

/**
 * Part names in an OPC package, read from the zip local file headers.
 *
 * Deliberately not a zip library: names are stored uncompressed in the header, so scanning for the
 * PK\x03\x04 signature and reading the name field is enough to answer "is this part still here"
 * without inflating anything or pulling a dependency into the test.
 */
const partNames = (zip: Uint8Array): string[] => {
  const dv = new DataView(zip.buffer, zip.byteOffset, zip.byteLength);
  const names: string[] = [];
  for (let i = 0; i + 30 <= zip.length; i++) {
    if (dv.getUint32(i, true) !== 0x04034b50) continue;
    const nameLen = dv.getUint16(i + 26, true);
    const start = i + 30;
    if (start + nameLen > zip.length) break;
    names.push(new TextDecoder().decode(zip.subarray(start, start + nameLen)));
  }
  return names;
};

/**
 * Every part of an OPC package, decompressed, by name.
 *
 * Walks the central directory rather than the local headers: sizes there are always correct, where
 * a local header carries zeroes whenever the entry was written with a data descriptor. Inflation
 * uses DecompressionStream, which is why this lives in the browser project - Node's zlib is not
 * available here and a zip dependency would be a lot of supply chain for one assertion.
 */
const readParts = async (zip: Uint8Array): Promise<Map<string, Uint8Array>> => {
  const dv = new DataView(zip.buffer, zip.byteOffset, zip.byteLength);

  let eocd = -1;
  for (let i = zip.length - 22; i >= 0; i--) {
    if (dv.getUint32(i, true) === 0x06054b50) {
      eocd = i;
      break;
    }
  }
  if (eocd < 0) throw new Error('not a zip: no end-of-central-directory record');

  const count = dv.getUint16(eocd + 10, true);
  let p = dv.getUint32(eocd + 16, true);
  const parts = new Map<string, Uint8Array>();

  for (let n = 0; n < count; n++) {
    const method = dv.getUint16(p + 10, true);
    const compressed = dv.getUint32(p + 20, true);
    const nameLen = dv.getUint16(p + 28, true);
    const extraLen = dv.getUint16(p + 30, true);
    const commentLen = dv.getUint16(p + 32, true);
    const localAt = dv.getUint32(p + 42, true);
    const name = new TextDecoder().decode(zip.subarray(p + 46, p + 46 + nameLen));

    // The local header repeats the name and extra fields, and its extra field length can differ
    // from the central one, so the data offset has to be computed from the local header.
    const start = localAt + 30 + dv.getUint16(localAt + 26, true) + dv.getUint16(localAt + 28, true);
    const raw = zip.slice(start, start + compressed);

    if (method === 0) {
      parts.set(name, raw);
    } else {
      const inflated = new Blob([raw]).stream().pipeThrough(new DecompressionStream('deflate-raw'));
      parts.set(name, new Uint8Array(await new Response(inflated).arrayBuffer()));
    }
    p += 46 + nameLen + extraLen + commentLen;
  }
  return parts;
};

const sameBytes = (a: Uint8Array, b: Uint8Array) =>
  a.length === b.length && a.every((x, i) => x === b[i]);

/**
 * The parts the model owns and re-renders on every save. Everything else must survive verbatim.
 *
 * This is the editable surface: the body, the style definitions, and the relationship part that
 * binds them. Everything outside it - theme, font table, numbering, settings, document properties,
 * media, embeddings - is carried through as opaque bytes.
 *
 * These are re-rendered rather than edited in place, so they come back larger even when nothing was
 * changed, mostly Word's namespace list. That is expected. What is not expected is any *other* name
 * appearing here, which is what the second test below asserts.
 *
 * Headers and footers used to be in this set and are deliberately not any more: they were being
 * re-rendered on every save from a flat paragraph list, which flattened a header table to loose
 * paragraphs on a document that had only been opened. They are now passed through unless edited.
 */
const REGENERATED = new Set([
  'word/_rels/document.xml.rels',
  'word/document.xml',
  'word/styles.xml',
]);

/**
 * Parts whose content the model does not fully represent, named individually because they are the
 * whole point of the fixture. Two are binary, and oleObject1.bin spans the full 0..255 byte range,
 * so any UTF-8 round-tripping or newline translation on the way through corrupts it.
 *
 * header1.xml is here because the fixture's header is a two-cell table - a letterhead - and the
 * header story the model keeps is a flat paragraph list. It can only come back intact by not being
 * re-rendered at all.
 */
const PASSTHROUGH = [
  'docProps/custom.xml',
  'word/embeddings/oleObject1.bin',
  'word/header1.xml',
  'word/media/image1.png',
  'word/theme/theme1.xml',
];

/** First index where two buffers differ, or where the shorter one ends. Null when identical. */
const firstDifference = (a: Uint8Array, b: Uint8Array): number | null => {
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i++) if (a[i] !== b[i]) return i;
  return a.length === b.length ? null : n;
};

/** Assert two packages are byte-for-byte equal, reporting a readable window when they are not. */
const expectSameBytes = (a: Uint8Array, b: Uint8Array): void => {
  const at = firstDifference(a, b);
  expect(at === null, at === null ? undefined : describeDrift(a, b, at)).toBe(true);
};

/**
 * A readable failure for a byte mismatch.
 *
 * Dumping 1.3 KB of zip at a reviewer is useless, so this reports the lengths, the offset, and a
 * short hex-plus-ASCII window around it. In an OPC package the ASCII side is usually the tell: a
 * part name, an XML attribute, or the `PK` of a local file header.
 */
const describeDrift = (a: Uint8Array, b: Uint8Array, at: number): string => {
  const win = (buf: Uint8Array) => {
    const slice = [...buf.slice(Math.max(0, at - 8), at + 24)];
    const hex = slice.map((x) => x.toString(16).padStart(2, '0')).join(' ');
    const ascii = slice.map((x) => (x >= 0x20 && x < 0x7f ? String.fromCharCode(x) : '.')).join('');
    return `${hex}\n    ${ascii}`;
  };
  return [
    `saved bytes differ from the file as opened at offset ${at}`,
    `  original (${a.length} bytes): ${win(a)}`,
    `  saved    (${b.length} bytes): ${win(b)}`,
  ].join('\n');
};

const nonBlank = (canvas: HTMLCanvasElement) => {
  const ctx = canvas.getContext('2d');
  const w = Math.min(canvas.width, 80);
  const h = Math.min(canvas.height, 80);
  const data = ctx?.getImageData(0, 0, w, h).data;
  return !!data && [...data].some((b) => b !== 0);
};

beforeAll(async () => {
  const res = await fetch(FIXTURE);
  expect(res.ok, `fixture not served at ${FIXTURE}`).toBe(true);
  sample = new Uint8Array(await res.arrayBuffer());
  // Guard the guard: an HTML 404 body would still parse as bytes and fail later in a confusing
  // place. A .docx is an OPC zip, so it starts with the local file header magic.
  expect([sample[0], sample[1]]).toEqual([0x50, 0x4b]);
});

beforeEach(async () => {
  container = document.createElement('div');
  container.style.width = '900px';
  container.style.height = '700px';
  document.body.append(container);
  view = await ScriptorView.create(container, { mode: 'edit' });
  await painted();
});

afterEach(() => {
  view.destroy();
  container.remove();
});

describe('a real .docx through the shipped wasm32 build', () => {
  it('parses and lays out into at least one page with content', async () => {
    view.loadDocx(sample);
    await painted();

    expect(view.pageCount()).toBeGreaterThanOrEqual(1);
    expect(view.wordCount()).toBeGreaterThan(0);
  });

  it('paints the loaded document rather than leaving the canvas blank', async () => {
    view.loadDocx(sample);
    await painted();

    // paint_page in the wasm crate feeds the canvas draw in view.ts. That handoff exists only in a
    // browser: the CLI render path used by visual-diff.ps1 does not go through it.
    expect(nonBlank(container.querySelector('canvas') as HTMLCanvasElement)).toBe(true);
  });

  it('keeps every part of the original package on save', async () => {
    // The invariant that actually protects a user who opens a document and presses Ctrl+S.
    //
    // Byte-identity of the whole file is deliberately NOT it: word/document.xml is re-rendered from
    // the model on every save, and the writer stamps fixed zip timestamps, so the container differs
    // by design. scriptor-ooxml's `roundtrip` (the corpus gate) compares decompressed parts rather
    // than the container for exactly that reason - see diff_parts in scriptor-ooxml/src/lib.rs.
    //
    // What must hold is that nothing is dropped. Parts the model does not understand ride through
    // verbatim as source_parts; a part that vanishes between open and save is silent data loss, the
    // bug class CONTRIBUTING.md calls the most serious.
    view.loadDocx(sample);
    await painted();

    const before = partNames(sample);
    const after = partNames(view.toDocx());
    expect(before.length).toBeGreaterThan(0);

    const dropped = before.filter((n) => !after.includes(n));
    expect(dropped, `parts lost on save: ${dropped.join(', ')}`).toEqual([]);
  });

  it('returns non-modeled parts byte-identical, not merely present', async () => {
    // The strong version of the passthrough guarantee. Checking a part is still *named* in the
    // output would pass a part that came back re-encoded, re-indented or re-ordered, which is the
    // same data loss with a better disguise. This inflates both packages and compares content.
    view.loadDocx(sample);
    await painted();

    const before = await readParts(sample);
    const after = await readParts(view.toDocx());

    let compared = 0;
    for (const [name, original] of before) {
      const saved = after.get(name);
      expect(saved, `part dropped on save: ${name}`).toBeDefined();
      if (REGENERATED.has(name) || !saved) continue;
      compared++;
      expect(
        sameBytes(original, saved),
        `${name} changed on save: ${original.length}B -> ${saved.length}B`,
      ).toBe(true);
    }

    // Without this the whole test passes vacuously if readParts ever returns nothing.
    expect(compared, 'no verbatim parts were compared').toBe(before.size - REGENERATED.size);
    expect(compared).toBeGreaterThan(0);
  });

  it('carries binary and unmodelled parts through untouched', async () => {
    // The same guarantee as above, but naming the parts that matter so a failure says what was lost
    // rather than just how many bytes moved. These are the fixture's reason for existing: an
    // embedded binary object, a PNG, custom document properties and a theme, none of which the model
    // represents. oleObject1.bin spans the full 0..255 range, so a byte-exact match here also rules
    // out UTF-8 round-tripping and newline translation in the passthrough path.
    view.loadDocx(sample);
    await painted();

    const before = await readParts(sample);
    const after = await readParts(view.toDocx());

    for (const name of PASSTHROUGH) {
      const original = before.get(name);
      const saved = after.get(name);
      expect(original, `fixture is missing ${name}`).toBeDefined();
      expect(saved, `${name} was dropped on save`).toBeDefined();
      if (!original || !saved) continue;
      expect(
        sameBytes(original, saved),
        `${name} changed on save: ${original.length}B -> ${saved.length}B`,
      ).toBe(true);
    }
  });

  it('regenerates only the parts the model owns', async () => {
    // The other half of the same guarantee, and the one that keeps REGENERATED honest. Without it
    // the check above quietly weakens every time a part is added to that set. If a future change
    // starts rewriting _rels/.rels, or stops rewriting document.xml, this fails and someone has to
    // decide which of the two is the bug.
    view.loadDocx(sample);
    await painted();

    const before = await readParts(sample);
    const after = await readParts(view.toDocx());
    const changed = [...before]
      .filter(([name, data]) => {
        const saved = after.get(name);
        return !saved || !sameBytes(data, saved);
      })
      .map(([name]) => name);

    expect(new Set(changed)).toEqual(REGENERATED);
  });

  it('saves the same bytes every time, so re-saving does not drift', async () => {
    // Idempotence. The container is not comparable to the source, but it must be comparable to
    // itself: two saves of the same unedited document have to agree byte-for-byte, and a save of a
    // reopened save has to agree too. This is what catches a nondeterministic writer (hash-order
    // part emission, a real timestamp leaking in) and the classic "file grows a little every save"
    // bug, neither of which a part-name check would notice.
    view.loadDocx(sample);
    await painted();

    const first = view.toDocx();
    const again = view.toDocx();
    expectSameBytes(first, again);

    view.loadDocx(first);
    await painted();
    expectSameBytes(first, view.toDocx());
  });

  it('re-serializes to a package the same build can read back', async () => {
    view.loadDocx(sample);
    await painted();
    const before = view.wordCount();

    const out = view.toDocx();
    expect([out[0], out[1]]).toEqual([0x50, 0x4b]);

    view.loadDocx(out);
    await painted();
    // Not a byte-stability claim - crates/scriptor-crdt/tests/roundtrip.rs owns that, and asserts it
    // far more strictly. This only says the write path on wasm32 produced something the read path on
    // wasm32 accepts, which is the loop a browser host actually performs on every save-and-reopen.
    expect(view.wordCount()).toBe(before);
  });

  it('replaces the previous document instead of appending to it', async () => {
    view.loadDocx(sample);
    await painted();
    const first = view.wordCount();

    view.loadDocx(sample);
    await painted();
    expect(view.wordCount()).toBe(first);
  });

  it('rejects a truncated package by throwing, and keeps the open document', async () => {
    // Not a fuzz test. It pins the contract a host needs for a corrupt upload, which turns out to
    // be a good one and is worth locking in: loadDocx throws rather than swallowing, and it throws
    // out of ScriptorDoc.openDocx before anything on the view is reassigned, so the document
    // already open is still there afterwards. Note this differs from edit(), which catches and
    // reports to console.error - a failed edit is silent, a failed load is not.
    view.loadDocx(sample);
    await painted();
    const before = view.wordCount();

    const truncated = sample.slice(0, Math.floor(sample.length / 2));
    expect(() => view.loadDocx(truncated)).toThrow(/zip|EOCD|docx/i);
    await painted();

    expect(view.wordCount()).toBe(before);
    expect(container.querySelector('canvas')).not.toBeNull();

    // And the view is not wedged: a good package still loads afterwards.
    view.loadDocx(sample);
    await painted();
    expect(view.wordCount()).toBe(before);
  });
});
